version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_VIBE_LOGGER_ENABLED=true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - GO_ENV=development
      - VIBE_LOGGER_ENABLED=true
      - VIBE_LOGGER_LEVEL=debug
      - GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY}
    working_dir: /app
    command: go run main.go

  # 開発用のポートフォワーディング
  dev-tools:
    image: alpine:latest
    command: tail -f /dev/null
    volumes:
      - .:/workspace